lelari/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')), # adicionar esta linha
    path('lelari1/', include('lelari1.urls')),
    path('admin/', admin.site.urls),
]

lelari1/urls.py
from django.urls import path

from . import views

app_name = 'lelari1'
urlpatterns = [
    path('', views.BookListView.as_view(), name='index'),
    path('search/', views.search_lelari1, name = 'search'),
    path('create/', views.create_book, name='create'),
    path('<int:pk>/', views.BookDetailView.as_view(), name='detail'),
    path('update/<int:book_id>/', views.update_book, name='update'),
    path('delete/<int:book_id>/', views.delete_book, name='delete'),
    path('<int:book_id>/comment/', views.create_comment, name='comment'),
    path('category/', views.CategoryListView.as_view(), name = 'category'),
    path('category/list', views.CategoryCreateView.as_view(), name ='category-list' )

    
    #path('update/<int:pk>/', views.BookUpdateView.as_view(), name='update'),
    #path('delete/<int:pk>/', views.BookDeleteView.as_view(sucess_url="index:lelari1"), name='delete'),
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

lelari1/models.py
from django.db import models
from django.conf import settings


class Book(models.Model):
    name = models.CharField(max_length=255)
    post_date = models.IntegerField()
    poster_url = models.URLField(max_length=200, null=True)

    def __str__(self):
        return f'{self.name} ({self.post_date})'


class Review(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    likes = models.IntegerField(default=0)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'


class Comment(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete = models.CASCADE,
    )

    text = models.CharField(max_length=255)
    publi_date = models.DateTimeField()
    #book = models.ForeignKey(Book, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.text}" ({self.publi_date}) - {self.author.username}'

class Category(models.Model):
    name = models.CharField(max_length=255)
    descr = models.CharField(max_length=255)
    def __str__(self):
        return f'"{self.descr}" {self.name}'

staticpages/models.py
from django.db import models

# Create your models here.

lelari1/forms.py
from django.forms import ModelForm
from .models import Book, Comment, Category


class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = [
            'name',
            'post_date',
            'poster_url',
        ]
        labels = {
            'name': 'Título',
            'post_date': 'Data de Lançamento',
            'poster_url': 'URL do Poster',
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'author',
            'text',
            'publi_date',
        ]

        labels = {
            'author': 'Usuário',
            'text': 'Comentário',
            'publi_date': 'Data da postagem'
        }

class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = [
            'name',
            'descr',
        ]
        labels = {
            'name': 'Título',
            'descr': 'Descrição'
        }

lelari1/views.py
from django.shortcuts import render, get_object_or_404

from django.http import HttpResponse
from django.http import HttpResponseRedirect
from .temp_data import book_data
from django.urls import reverse
from .models import Book, Comment, Category
from django.views import generic
from django.urls import reverse_lazy
from .forms import BookForm, CommentForm, CategoryForm

class BookListView(generic.ListView):
    model = Book
    template_name = 'lelari1/index.html'

class BookDetailView(generic.DetailView):
    model = Book
    template_name = 'lelari1/detail.html'

# class BookDeleteView(generic.DeleteView):
    #model = Book
    #template_name = 'lelari1/delete.html'
    #sucess_url = reverse_lazy ('index:lelari1')

#class BookUpdateView(generic.UpdateView):
    #model = Book
    #template_name = 'lelari1/update.html'
    #fields = ['name']
    #def get_absolute_url(self):
        #return  reverse('lelari1:detail', args=(book.id, ))


def detail_book(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    context = {'book': book}
    return render(request, 'lelari1/detail.html', context)

def list_lelari1(request):
    book_list = Book.objects.all()
    context = {"book_list": book_list}
    return render(request, 'lelari1/index.html', context)


def search_lelari1(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        book_list = Book.objects.filter(name__icontains=search_term)
        context = {"book_list": book_list}
    return render(request, 'lelari1/search.html', context)

def create_book(request):
    if request.method == 'POST':
        form = BookForm(request.POST)
        if form.is_valid():
            book_name = request.POST['name']
            book_post_date = request.POST['post_date']
            book_poster_url = request.POST['poster_url']
            book = Book(name= book_name, post_date = book_post_date, 
                        poster_url= book_poster_url)
            book.save()
            return HttpResponseRedirect(
                reverse('lelari1:detail', args=(book.id,) ))
    else:
        form = BookForm()
        context = {'form': form}
        return render(request, 'lelari1/create.html', context)

def update_book(request, book_id):
    book = get_object_or_404(Book, pk=book_id)

    if request.method == "POST":
        if form.is_valid():
            book.name = request.POST['name']
            book.post_date = request.POST['post_date']
            book_poster_url = request.POST['poster_url']
            book.save()
            return HttpResponseRedirect(
                reverse('lelari1:detail', args=(book.id, )))
    else:
        form= BookForm(
            initial ={
                'name': book.name,
                'post_date': book.post_date,
                'poster_url': book.poster_url
            }
        )

    context = {'book': book, 'form': form}
    return render(request, 'lelari1/update.html', context)


def delete_book(request, book_id):
    book = get_object_or_404(Book, pk=book_id)

    if request.method == "POST":
        book.delete()
        return HttpResponseRedirect(reverse('lelari1:index'))

    context = {'book': book}
    return render(request, 'lelari1/delete.html', context)

def create_comment(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_author = form.cleaned_data['author']
            comment_text = form.cleaned_data['text']
            comment_publi_date = form.cleaned_data['publi_date']
            comment = Comment(author=comment_author,
                            text=comment_text,
                            publi_date = comment_publi_date
                            #book=book
                            )
            comment.save()
            return HttpResponseRedirect(
                reverse('lelari1:detail', args=(book_id, )))
    else:
        form = CommentForm()
    context = {'form': form, 'book': book}
    return render(request, 'lelari1/comment.html', context)

class CategoryListView(generic.ListView):
    model = Category
    template_name = 'lelari1/category.html'

class CategoryCreateView(generic.CreateView):
    model = Category
    templeta_name = 'lelari1/category_list.html'
    fields = ['nome', 'descr']
    sucess_url = reverse_lazy('lelari1:category')

staticpages/views.py
from django.shortcuts import render


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

staticpages/templates/base.html
{% load static %} <!-- adicione esta linha -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Lê Lari!
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" /> <!-- adicione esta linha -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"> <!-- adicione esta linha -->
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="{% static 'undraw_appreciation_vmef.svg' %}"> </a> <!-- adicione esta linha -->
        <nav id="navegacao-principal">
            <ul>
                <li><a href="{% url 'lelari1:index' %}">Livros</a></li>
                <li><a href="{% url 'lelari1:category' %}">Categorias</a></li>
                <li><a href="{% url 'about' %}">Sobre</a></li>
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2022</small>
        </p>
    </footer>
</body>

</html>

staticpages/templates/lelari1/category.html
{% extends 'base.html' %}

{% block title %}
Categorias
{% endblock title %}

{% block content %}
<h2>Categorias de Livros</h2>

<section>
    {% for category in category_category %}
    <hr>
    <article>
        <header>
            <h3>{{category.name}} (de {{ category.author }}) </h3>
        </header>
        <div class="lista-de-cards">
            {% for book in category.book.all %}
            <div class="card">
                <a href="{% url 'lelari1:detail' book.id %}"><img src="{{ book.poster_url }}"
                        alt="Poster do Livro{{ book.name}}"></a>
                <p>{{ book.name }} ({{ book.post_date }})</p>
            </div>
            {% endfor %}
        </div>
    </article>
    {% endfor %}

    <a href="{% url 'lelari1:category-list' %}"><button>Crie sua Categoria</button></a>

</section>

{% endblock content %}

staticpages/templates/lelari1/category_list.html
{% extends 'base.html' %}

{% block title %}
Criar Livro
{% endblock title %}

{% block content %}
<h2>Criar Categoria</h2>

<form action="{% url 'lelari1:category-list' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

staticpages/templates/lelari1/comment.html
{% extends 'base.html' %}

{% block content %}
<h2>Comentar Livro {{ book.name }} ({{ book.post_date }})</h2>

<form action="{% url 'lelari1:comment' book.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Publicar Comentário</button>
</form>

<p><a href="{% url 'lelari1:detail' book.id %}">Voltar para a página do livro</a></p>
{% endblock content %}

staticpages/templates/lelari1/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir Novo Livro</h2>
<form method="POST" action="{% url 'lelari1:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

staticpages/templates/lelari1/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'lelari1:delete' book.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar o livro "{{ book.name }} ({{ book.post_date }})"?
    </p>
    <button type="submit">Apagar</button>
</form>

{% endblock content %}

staticpages/templates/lelari1/detail.html
{% extends 'base.html' %}

{% block title %}
{{ book.name }} ({{ book.post_date }}
{% endblock title %}

{% block content %}
<h2>Detalhes do livro {{ book.name }} ({{ book.post_date }})</h2>

<section class="dados-do-livro">
    <img src="{{ book.poster_url }}" alt="Poster do livro {{ book.name}}">
    <ul>
        <li>Nome: {{ book.name }}</li>
        <li>Ano de Lançamento: {{ book.post_date }} </li>
        {% if book.category_set.all %}
        <li>Incluso nas Categorias: {{ book.category_set.all|join:", " }} </li>
        {% endif %}
        <li><a href = "{% url 'lelari1:update' book.id %}">Editar</a></li>
        <li><a href = "{% url 'lelari1:delete' book.id %}">Apagar</a></li>
    </ul>
</section>


<hr>

<section>
    <header>
        <h3>Comentários</h3>
    </header>
    <ul>
        {% if book.comment_set.all %}
            {% for comment in book.comment_set.all %}
                <figure>
                    <blockquote>
                        "{{ comment.text }}"
                    </blockquote>
                    <figcaption>—{{ comment.author }}
                </figure>
            {% endfor %}
        {% else %}
            <p>Ainda não existe nenhum comentário para este livro.</p>
        {% endif %}
    </ul>
</section>

</ul>
    
<hr>

<a href="{% url 'lelari1:comment' book.pk %}"><button>Deixe seu comentário</button></a>
</section>

{% endblock content %}

staticpages/templates/lelari1/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Todos os Livros</h2>
<section>
    <p>Muitos resultados? <a href="{% url 'lelari1:search' %}">Buscar Livros</a></p>
    <p>Não encontrou o livro? <a href="{% url 'lelari1:create' %}">Adicionar Novo Livro</a></p>
</section>
{% if book_list %}
<section class="lista-de-cards">
    {% for book in book_list %}
    <article class="card">
        <a href="{% url 'lelari1:detail' book.id %}"><img src="{{ book.poster_url }}"
                alt="Poster do livro {{ book.name}}"></a>
        <p>{{ book.name }} ({{ book.post_date }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum livro.</p>
{% endif %}

{% endblock content %}

staticpages/templates/lelari1/search.html
{% extends 'base.html' %}

{% block content %}
<h2>Busca de Livros por Nome</h2>
<form action="{% url 'lelari1:search' %}">
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if book_list %}
<section class="lista-de-cards">
    {% for book in book_list %}
    <article class="card">
        <img src="{{ book.poster_url }}" alt="Poster do livro {{ book.name}}">
        <p>{{ book.name }} ({{ book.post_date }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum livro para a busca.</p>
{% endif %}

{% endblock content %}

staticpages/templates/lelari1/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Atualizar Dados do Livro {{ book.name }} ({{ book.post_date}})</h2>
<form method="POST" action="{% url 'lelari1:update' book.id%}">
    {% csrf_token %}
    {{ form.as_p}}
    <button type="submit">Atualizar</button>
</form>

{% endblock content %}

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>Sobre este site</h2>
{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h1><i>Lê Lari</i></h1>
<p>A Página para Comunidade de Leitores</p>
{% endblock content %}